account/urls.py
# urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'

urlpatterns=[
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html'), name='login'),
    path('register/', views.register, name='register'),
]
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import RegisterView

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html'), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
     path('logout/', auth_views.LogoutView.as_view(next_page='account:login'), name='logout')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('account.urls')),
    path("data/", include('data.urls')),
]

data/urls.py
from django.urls import path
from . import views

app_name = 'data'

urlpatterns = [
    path('arrest/', views.arrest, name='arrest'),
    path('safemap/', views.safemap, name='safemap'),
    path('region/', views.region, name='region'),
    path('yongsan/', views.yongsan, name='yongsan'),
    path('gangnam/', views.gangnam, name='gangnam'),
    path('dongjak/', views.dongjak, name='dongjak'),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.main, name='main'),

]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render


def main(request) :
    return render(request, 'home/home.html')

home/templates/home/home.html
{% load static %} 
<!DOCTYPE html>
<html lang="en">
   <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Crime Insight</title>
        {% include 'home/navbar.html' %}
   </head> 
   <body class="sb-nav-fixed">
     <section id="hero" class="d-flex align-items-center">
       <div id="layoutSidenav" style="width=100%">
         <div id="layoutSidenav_content">
           <main>
             <div class="container position-relative" data-aos="fade-up" data-aos-delay="100">
               <div class="row justify-content-center">
                 <div class="col-xl-7 col-lg-9 text-center">
                   <h1>Welcome to Crime Insight</h1>
                     <h2>범죄 정보 시각화 웹사이트입니다.</h2>
                 </div>
               </div>
               
               <div class="row icon-boxes justify-content-center">
                 <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="200">
                   <div class="icon-box">
                     <div class="icon"><i class="ri-stack-line"></i></div>
                     <h4 class="title"><a href="{% url 'data:safemap' %}">Safe Map</a></h4>
                     <p class="description">안심귀가를 위해 안심 CCTV의 위치를 표시해주는 지도입니다.</p>
                   </div>
                 </div>
              
                 <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="700">
                   <div class="icon-box">
                     <div class="icon"><i class="ri-palette-line"></i></div>
                     <h4 class="title"><a href="{% url 'data:region' %}">장소별 범죄 정보</a></h4>
                     <p class="description">각 지역구에 대한 장소별 범죄 발생 현황에 대해 살펴봅니다.</p>
                   </div>
                   </div>
         
                 <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="400">
                   <div class="icon-box">
                     <div class="icon"><i class="ri-command-line"></i></div>
                     <h4 class="title"><a href="{% url 'data:arrest' %}">범죄 발생 및 검거 정보</a></h4>
                     <p class="description">지역구별 범죄 발생 및 검거 현황에 대해 살펴봅니다.</p>
                   </div>
                 </div>
             </div>
           </main>
         </div>
       </div>            
     </section>
     <footer class="py-4 bg-light mt-auto">
         <div class="container-fluid px-4">
             <div class="d-flex align-items-center justify-content-between small">
                 <div class="text-muted">Copyright &copy; Your Website 2023</div>
                 <div>
                     <a href="#">Privacy Policy</a>
                     &middot;
                     <a href="#">Terms &amp; Conditions</a>
                 </div>
             </div>
         </div>
     </footer>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
     <script src="{% static 'js/scripts.js' %}"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
     <script src="{% static 'assets/demo/chart-area-demo.js' %}"></script>
     <script src="{% static 'assets/demo/chart-bar-demo.js' %}"></script>
     <script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
     <script src="{% static 'js/datatables-simple-demo.js' %}"></script>
     <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
     <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
     <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
     <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
     <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
     <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
     <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

<!-- Template Main JS File -->
     <script src="{% static 'assets/js/main.js' %}"></script>
 </body>
</html>

home/templates/home/navbar.html
{% load static %} 
<link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
<link href="{% static 'css/styles.css' %}" rel="stylesheet" />
<link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
<script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark ">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="/">Crime Insight</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    {% if user.is_authenticated %}
                        <!-- 사용자가 로그인되어 있을 때 -->
                        <p>안녕하세요, {{ user.username }}님!</p>
                        <li><a class="dropdown-item" href="{% url 'account:logout' %}">로그아웃</a></li>
                    {% else %}
                        <!-- 사용자가 로그인되어 있지 않을 때 -->
                        <li><a class="dropdown-item" href="{% url 'account:login' %}">로그인</a></li>
                    {% endif %}
                    
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <a class="nav-link" href="index.html">
                        <a class="nav-link" href="{% url 'data:safemap' %}">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Safe Map
                        </a>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            범죄 통계
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="layout-static.html">지역별 통계</a>
                                <a class="nav-link" href="layout-sidenav-light.html">장소별 통계</a>
                                <a class="nav-link" href="layout-sidenav-light.html">검거율 통계</a>
                                <a class="nav-link" href="{% url 'data:region' %}">지역별 통계</a>
                                <a class="nav-link" href="{% url 'data:yongsan' %}">장소별 통계</a>
                            </nav>
                        </div>

                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                        <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                        소통 게시판
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="layout-static.html">위험 구역 제보</a>
                                <a class="nav-link" href="layout-sidenav-light.html">CCTV 설치 신청</a>
                                <a class="nav-link" href="layout-sidenav-light.html">자유 게시판</a>
                            </nav>
                        </div>
                        <div class="sb-sidenav-menu-heading">참고 자료</div>
                        <a class="nav-link" href="charts.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                            범죄 관련 데이터 수집
                        </a>
                        <a class="nav-link" href="tables.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            최근 범죄 뉴스
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Love Lee:</div>
                    Crime Insight
                </div>
            </nav>
        </div>
    </div>
</body>